//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class myphamEntities : DbContext
    {
        public myphamEntities()
            : base("name=myphamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<hdn> hdns { get; set; }
        public virtual DbSet<hoadonban> hoadonbans { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<ncc> nccs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<chitiethdb> chitiethdbs { get; set; }
        public virtual DbSet<chitiethdn> chitiethdns { get; set; }
    
        public virtual ObjectResult<SP_SearchKH_Result> SP_SearchKH(Nullable<int> sdt)
        {
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchKH_Result>("SP_SearchKH", sdtParameter);
        }
    
        public virtual ObjectResult<SP_SearchNCC_Result> SP_SearchNCC(string tenncc)
        {
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchNCC_Result>("SP_SearchNCC", tennccParameter);
        }
    
        public virtual ObjectResult<SP_SearchNV_Result> SP_SearchNV(Nullable<int> sdt)
        {
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchNV_Result>("SP_SearchNV", sdtParameter);
        }
    
        public virtual ObjectResult<SP_SearchSP_Result> SP_SearchSP(string tensp)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchSP_Result>("SP_SearchSP", tenspParameter);
        }
    
        public virtual ObjectResult<GetHoaDonBan_Result> GetHoaDonBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHoaDonBan_Result>("GetHoaDonBan");
        }
    
        public virtual ObjectResult<SP_SearchHDB_Result> SP_SearchHDB(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<int> sdt)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchHDB_Result>("SP_SearchHDB", tungayParameter, denngayParameter, sdtParameter);
        }
    
        public virtual ObjectResult<SearchHDB_Result> SearchHDB(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<int> sdt)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchHDB_Result>("SearchHDB", tungayParameter, denngayParameter, sdtParameter);
        }
    
        public virtual ObjectResult<SearchHDN_Result> SearchHDN(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string tenncc)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchHDN_Result>("SearchHDN", tungayParameter, denngayParameter, tennccParameter);
        }
    }
}
